### ISSUE TITLE
/key/littlewin-server

### ISSUE THREAD

**Issue by huang303513** [littlewin-wang/littlewin.server#5]
'/key/littlewin-server'里面的内容是什么啊。能把他贴出来吗？管家部分你可以替换啊，或者不替换也可以啊。谢谢，，不然跑步起来。

**Comment by huang303513** [comment]
let { AUTH, QINIU, EMAIL, AKISMET } = require(process.env.HOME.concat('/key/littlewin-server'))这个文件里面的结构。

**Comment by littlewin-wang** [comment]
问这个问题的小伙伴略多，开了个wiki
https://github.com/littlewin-wang/littlewin.server/wiki/%E5%AF%86%E9%92%A5%E6%95%B0%E6%8D%AE%E6%96%87%E4%BB%B6
